### ISSUE TITLE
How to convert a 3d array into a binary format that I could open it as a binary file directly from Matlab without any conversion or using unpack?

### ISSUE THREAD

**Issue by sharifzadeh** [HebiRobotics/MFL#74]
Given there is a large 3d array as **data = float[1000][128][128]**

I will need to convert the above 3d array into a binary format that I could open directly from Matlab without any conversion or using unpack:

j_id= fopen('/data.out', 'rb'); 
dj = fread(j_id, 'float32') 
fclose(j_id);

So how to convert the array into an appropriate binary/byte array output stream?

Thanks

**Comment by ennerf** [comment]
The most performant way would be to create a custom adapter that writes the data directly to the sink. You can mostly copy & paste code from [DMatrixWrapper](https://github.com/HebiRobotics/MFL/blob/main/mfl-ejml/src/main/java/us/hebi/matlab/mat/ejml/DMatrixWrapper.java) and override [getDimensions()](https://github.com/HebiRobotics/MFL/blob/main/mfl-ejml/src/main/java/us/hebi/matlab/mat/ejml/AbstractMatrixWrapper.java#L84-L88) to return `int[3]`, 

Note that MATLAB expects the data to be written in column-major order, so you'll likely have to iterate over the last dimension first, e.g., `float[k][j][i]` rather than `float[i][j][k]`.

**Comment by sharifzadeh** [comment]
Thanks for your email but I did not find where and how to convert the sink
to an appropriate byte array output stream that I could open in Matlab as a
binary format: fopen(path, 'rb')

**Comment by ennerf** [comment]
This library writes files in the binary `.mat` file format that MATLAB supports natively. Please check the [readme](https://github.com/HebiRobotics/MFL#creating-and-writing-mat-files) and the [Test classes](https://github.com/HebiRobotics/MFL/blob/main/mfl-ejml/src/test/java/us/hebi/matlab/mat/ejml/Mat5EjmlTest.java#L50-L83) on how to write data to disk.

Once you have a `.mat` file, you can load them in MATLAB using [load](https://www.mathworks.com/help/matlab/ref/load.html), e.g., `dataStruct = load('savedFile.mat')`.

You do not need to deal with raw filepointers all.
